### PR TITLE
Multiple changes to prepare for Maven Central release

### PR DESCRIPTION
**Pull request by sangupta**
This pull request brings in a lot of minor changes that are described below:

* First and foremost change is to remove the modularization in Maven pom.xml - thus, the top-level POM file is itself the project POM. Also, aligned to the same is reorganization of code into maven convention `src/main/java` and `src/test/java` folders.

* Next is to remove the Eclipse IDE specific files. These can be auto-generated via Maven using `mvn eclipse:eclipse` and thus could be removed.

* Updated the `.gitignore` file to remove more standard noise across platforms.

* Reorganized the codebase to move implementation specific files to their respective sub-packages. The test files were moved in a similar fashion. This just makes it a little easier to find what we are looking for.

* Added Apache version 2 license header to all files for **Stoyanr**

* Reformatted javadocs using Eclipse to make them a little extra readable when looking at pure source code.

* Added **travis-ci** integration - it would be great if you could enable the same at your end and then update the badge with your repo location. This was useful in finding the VM crash on Linux when running test cases.

* Added **coveralls.io** test coverage integration - this helps us to include a badge to indicate the current coverage - will let one know the health of the project.

* Minor code refactorings - renamed a few variables to make more sense. Added the **this** qualifier when accessing class level attributes. 

### TODO:

I created a simple **travis-ci** integration and see that the tests fail/crash the VM when run on Linux. I haven't yet had time to debug the issue but will be doing it soon - to fix the test cases and also help increase code coverage to make the library more robust.

**Update:** I debugged the test issue failure on `travis-ci` and it seems the tests are being killed due to exhaustion of resources. I used an Ubuntu 14 machine for the same. A simple `/usr/bin/time -v mvn test` produces that the RSS size goes above 1.2GB while testing - the build workers have a 3GB total limit - may be we are hitting that. Need more time to debug this. As a fallout of this debug - I found that some tests do fail randomly.

Secondly, I need to clean up the README file once the pull-request is merged for all the changes.

### Work of Thanks

Last but not the least, thanks **Stoyanr** for working out this wonderful library.

### CODE REVIEW

**Comment by stoyanr** [comment]
@sangupta, thanks for the PR. I do appreciate your help and the effort you have put into this. Most things make perfect sense and I will definitely merge this PR. However, there are a few minor (I hope) things that I would like to see corrected before that:
* I do not consider the way the Javadocs are formatted right now an improvement. There is a kind of mess with spaces vs. tabs which causes the comments to look oddly formatted with certain tab widths. In general I don't use tabs for formatting at all and would not accept them in Javadoc comments as well. Please either correct this or (even better from my perspective) rollback your formatting changes to the Javadoc comments. 
* The README contains a section at the top with the title "Changes to the original project". This **is** the original project now, so this section is badly named and also misplaced. It also repeats information already available in commits. I would prefer that you remove this section. If you believe it contains information that is valuable for the README (I couldn't find any), please find the appropriate README section and put it there.
* With the new repo structure that you introduced, some links in the README no longer work, please fix this.
* The `pom.xml` file also contains some badly formatted XML (again spaces vs. tabs), and the `scm` section contains a link to your Git repo instead of this one, please fix this as well.
* The old top-level `pom.xml` is no longer needed, I would prefer that you remove it.

**Comment by sangupta** [comment]
@stoyanr Makes sense. I would make the changes accordingly and fix the PR by max tomorrow.

If you agree, I can look into converting tabs to spaces using some automated tool and thus keep the javadoc formatting (I did it via Eclipse so am sure there would be a way) - else will revert the same to original formatting.

**Comment by sangupta** [comment]
@stoyanr The following changes are done:

* Reformat `pom.xml` using spaces and changes for repo origination
* Removed old parent `pom.xml` file
* Removed `changes in this fork` section from `readme`

**Comment by sangupta** [comment]
@stoyanr I have updated all code to use spaces rather than tabs in all files (including Java code) with an indentation of 4 spaces. Let me know if it works else I can rework them to original.

**Comment by stoyanr** [comment]
@sangupta, thanks once again for your contributions! I merged the PR and released to Evictor 1.0.0 to Maven Central.

**Comment by sangupta** [comment]
@stoyanr Thanks a bunch for working this up. I have a side-project that depends on this I can release now :)

**Pull request merged**
